import:
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-base-r4.1.yml
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-vms-r4.1.yml
language: python
python: '3.5'
jobs:
  include:
    - python: '3.6'  # needs to match bionic
      virtualenv:
        system_site_packages: true
      install:
        - sudo apt-get -y install python3-gi gir1.2-gtk-3.0
        - pip install --quiet -r ci/requirements.txt
      env: TESTS_ONLY=1
      script:
       - ./run-tests
       - shellcheck -e SC1117 $(grep -l '^#!/bin/\(ba\)\?sh' $(git ls-files))
      after_success:
       - codecov
    - stage: deploy
      python: '3.5'
      env: DIST_DOM0=fc31 TESTS_ONLY=
      script: ~/qubes-builder/scripts/travis-deploy
  allow_failures:
    # no yum/dnf currently in bullseye
    - env: DISTS_VM=bullseye USE_QUBES_REPO_VERSION=4.1 USE_QUBES_REPO_TESTING=1
